version: '3'
services:
  server:
    build: ./server
    expose:
      - 3001
    ports:
      - 3001:3001
    volumes:
      - ./server/src:/srv/app/micc-delivery-challenge-server/src
    command: npm start
  client:
    build: ./client
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/srv/app/micc-delivery-challenge-client/src
      - ./client/public:/srv/app/micc-delivery-challenge-client/public
    command: npm start